name: Android CI

on: [ push ]

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.repository == 'simonnorberg/kortholt'
    timeout-minutes: 30
    env:
      TERM: dumb
      ORG_GRADLE_PROJECT_OSSRH_USERNAME: ${{ secrets.ORG_GRADLE_PROJECT_OSSRH_USERNAME }}
      ORG_GRADLE_PROJECT_OSSRH_PASSWORD: ${{ secrets.ORG_GRADLE_PROJECT_OSSRH_PASSWORD }}
      ORG_GRADLE_PROJECT_SONATYPE_STAGING_PROFILE_ID: ${{ secrets.ORG_GRADLE_PROJECT_SONATYPE_STAGING_PROFILE_ID }}
      ORG_GRADLE_PROJECT_SIGNING_KEY: ${{ secrets.ORG_GRADLE_PROJECT_SIGNING_KEY }}
      ORG_GRADLE_PROJECT_SIGNING_PASSWORD: ${{ secrets.ORG_GRADLE_PROJECT_SIGNING_PASSWORD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Set up JDK
        uses: actions/setup-java@v4.2.1
        with:
          distribution: 'zulu'
          java-version: 17

      - name: Update submodules
        run: git submodule update --init --recursive

      - name: Build and publish
        run: ./gradlew ktlintCheck lintDebug publishToMavenLocal

      - name: Upload release
        if: startsWith(github.ref, 'refs/heads/develop')
        run: ./gradlew publishReleasePublicationToSonatypeRepository
